name: PRs reviews reminder
on:
  schedule:
    # Every weekday every 2 hours during working hours, send notification 
    - cron: "0 14-23/2 * * 1-5"
jobs:
  pr-reviews-reminder:
   runs-on: ubuntu-latest
   steps:
   - uses: DavideViolante/pr-reviews-reminder-action@v1.3.0
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       webhook-url: ${{ secrets.TEAMS_WEBHOOK }}
       provider: 'msteams'
